name: PythonTesting
channels:
  - huggingface
  - defaults
dependencies:
  - aom=3.6.0=h313beb8_0
  - arrow-cpp=19.0.0=h0747fcf_5
  - aws-c-auth=0.9.0=h79febb2_2
  - aws-c-cal=0.9.2=h79febb2_1
  - aws-c-common=0.12.4=h79febb2_0
  - aws-c-compression=0.3.1=h79febb2_2
  - aws-c-event-stream=0.5.6=h79febb2_0
  - aws-c-http=0.10.4=h79febb2_0
  - aws-c-io=0.21.4=h79febb2_0
  - aws-c-mqtt=0.13.3=h387b88a_0
  - aws-c-s3=0.8.7=h79febb2_0
  - aws-c-sdkutils=0.2.4=h79febb2_1
  - aws-checksums=0.2.7=h79febb2_1
  - aws-crt-cpp=0.34.0=hee39554_0
  - aws-sdk-cpp=1.11.638=h35fa3df_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py313ha35b7ea_0
  - brotlicffi=1.0.9.2=py313h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.9.9=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - certifi=2025.8.3=py313hca03da5_0
  - cffi=1.17.1=py313h3eb5a62_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.1=h313beb8_0
  - filelock=3.17.0=py313hca03da5_0
  - fontconfig=2.14.1=h6402c1e_3
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - fsspec=2025.7.0=py313h7eb115d_0
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=h313beb8_1
  - glog=0.5.0=h313beb8_1
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - huggingface_hub=0.29.2=py_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py313hca03da5_0
  - jpeg=9f=h2f69dba_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libavif=1.1.1=h80987f9_0
  - libbrotlicommon=1.0.9=h80987f9_9
  - libbrotlidec=1.0.9=h80987f9_9
  - libbrotlienc=1.0.9=h80987f9_9
  - libcurl=8.15.0=hcdd2897_0
  - libcxx=20.1.8=h8869778_0
  - libdeflate=1.22=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.2=hdc2269c_0
  - libgrpc=1.71.0=h62f6fdd_0
  - libiconv=1.16=h80987f9_3
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.30=hf2bb037_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=5.29.3=h14f15fd_1
  - libre2-11=2024.07.02=h313beb8_0
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.15.0=hc678506_3
  - libtiff=4.7.0=h91aec0a_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.8=h0b34f26_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - ncurses=6.5=hee39554_0
  - numexpr=2.11.0=py313hf08b1b5_1
  - numpy=2.3.3=py313h4bb6f22_0
  - numpy-base=2.3.3=py313h23175f9_0
  - openjpeg=2.5.2=hba36e21_1
  - openssl=3.0.17=h4ee41c1_0
  - orc=2.1.1=h55d209b_0
  - packaging=25.0=py313hca03da5_0
  - pandas=2.3.2=py313h17050e6_0
  - pcre2=10.42=hb066dcc_1
  - pillow=11.3.0=py313h6dd570d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - pyarrow=19.0.0=py313hee39554_2
  - pycparser=2.23=py313hca03da5_0
  - pysocks=1.7.1=py313hca03da5_0
  - python=3.13.7=hc28b8d9_100_cp313
  - python-dateutil=2.9.0post0=py313hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=1_cp313
  - pytz=2025.2=py313hca03da5_0
  - pyyaml=6.0.2=py313h80987f9_0
  - re2=2024.07.02=h48ca7d4_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py313hca03da5_0
  - setuptools=72.1.0=py313hca03da5_0
  - six=1.17.0=py313hca03da5_0
  - snappy=1.2.1=h313beb8_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - tqdm=4.67.1=py313h7eb115d_0
  - typing-extensions=4.15.0=py313hca03da5_0
  - typing_extensions=4.15.0=py313hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py313hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - jinja2==3.1.6
      - joblib==1.5.2
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.5
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.8.0
prefix: /opt/anaconda3/envs/PythonTesting
